# Generated by Django 4.1.2 on 2022-12-18 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_detail', models.CharField(max_length=500)),
                ('salary', models.IntegerField()),
                ('education', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('hiring_insight', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('hr_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jobseekar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('member', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photopath', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('education', models.CharField(max_length=400)),
                ('resume', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.jobseekar')),
            ],
        ),
    ]
