# Generated by Django 4.1.2 on 2022-12-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_remove_jobseekerprofile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='education',
        ),
    ]
