# Generated by Django 4.1.2 on 2022-12-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0005_remove_jobseekerprofile_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='user',
        ),
    ]
