# Generated by Django 4.1.2 on 2022-12-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0007_remove_jobseekar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='photopath',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
