# Generated by Django 4.1.2 on 2022-12-21 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0008_alter_jobseekerprofile_photopath'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='jobseeker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coaching.jobseekar'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
