# Generated by Django 4.1.2 on 2022-12-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0009_jobseekerprofile_jobseeker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(default='/media/download.pnj', upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
