# Generated by Django 4.1.2 on 2022-12-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0011_alter_job_company_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='username',
            new_name='name',
        ),
    ]
