# Generated by Django 4.1.2 on 2022-12-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0012_rename_username_jobseekerprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_logo',
        ),
    ]
