# Generated by Django 4.1.2 on 2022-12-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0013_remove_job_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(default='/media/download.png', upload_to=''),
        ),
    ]
