# Generated by Django 4.1.2 on 2022-12-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0015_remove_job_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.ImageField(default='/static/download.png', upload_to=''),
        ),
    ]
