# Generated by Django 4.1.2 on 2022-12-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0018_remove_jobseekar_member_job_posted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekar',
            name='member',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='photopath',
            field=models.ImageField(default='none', upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(default='none', upload_to=''),
        ),
    ]
