# Generated by Django 4.1.2 on 2022-12-27 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0019_jobseekar_member_alter_jobseekerprofile_photopath_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.CharField(max_length=50)),
                ('Jobseekar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.jobseekar')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.job')),
            ],
        ),
    ]
