# Generated by Django 4.1.2 on 2022-12-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0020_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='programming_language',
            field=models.CharField(default='', max_length=50),
        ),
    ]
