# Generated by Django 4.1.2 on 2022-12-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0022_alter_job_job_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='apply_date',
            field=models.DateTimeField(null=True),
        ),
    ]
