# Generated by Django 4.1.2 on 2022-12-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0023_apply_apply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekar',
            name='course_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
