# Generated by Django 4.1.2 on 2022-12-30 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0024_jobseekar_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_date',
            field=models.DateField(default=datetime.date(2022, 12, 30)),
        ),
    ]
