# Generated by Django 4.1.2 on 2023-01-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0026_alter_job_posted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='hiring_insight',
            new_name='vacancy',
        ),
    ]
