# Generated by Django 4.1.2 on 2023-01-05 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0027_rename_hiring_insight_job_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(default=datetime.date(2023, 1, 5)),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.CharField(default='', max_length=200),
        ),
    ]
