# Generated by Django 4.1.2 on 2023-01-10 12:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0028_alter_apply_apply_date_alter_job_posted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(default=datetime.date(2023, 1, 10)),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_stream', models.CharField(max_length=50)),
                ('primary_percentage', models.CharField(max_length=50)),
                ('primary_year', models.CharField(max_length=50)),
                ('secondary_stream', models.CharField(max_length=50)),
                ('secondary_percentage', models.CharField(max_length=50)),
                ('secondary_year', models.CharField(max_length=50)),
                ('graduation_stream', models.CharField(max_length=50)),
                ('graduation_percentage', models.CharField(max_length=50)),
                ('graduation_year', models.CharField(max_length=50)),
                ('post_graduation_stream', models.CharField(blank=True, max_length=50, null=True)),
                ('post_graduation_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('post_graduation_year', models.CharField(blank=True, max_length=50, null=True)),
                ('jobseekerprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.jobseekerprofile')),
            ],
        ),
    ]
