# Generated by Django 4.1.2 on 2023-01-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0029_alter_job_posted_date_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduation_percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='post_graduation_percentage',
            field=models.IntegerField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='post_graduation_stream',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='post_graduation_year',
            field=models.IntegerField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='primary_percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='primary_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='secondary_percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='secondary_year',
            field=models.IntegerField(),
        ),
    ]
