# Generated by Django 4.1.2 on 2023-01-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0030_alter_education_graduation_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='post_graduation_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='post_graduation_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
