# Generated by Django 4.1.2 on 2023-01-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0032_alter_education_post_graduation_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='post_graduation_percentage',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='post_graduation_year',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
