# Generated by Django 4.1.2 on 2023-01-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0034_alter_education_jobseekerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='jobseekerprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coaching.jobseekar'),
        ),
    ]
