# Generated by Django 4.1.2 on 2023-01-19 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0036_jobseekerprofile_graduation_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(default=datetime.date(2023, 1, 19)),
        ),
    ]
