# Generated by Django 4.1.2 on 2023-01-24 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0038_alter_job_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(default=datetime.date(2023, 1, 24)),
        ),
    ]
